#!/bin/bash
echo "=== CYBERTRUCK NAVIGATION TEST ==="
echo ""
echo "1. Start the simulation (in Terminal 1):"
echo "   ros2 launch cybertruck_description complete_navigation.launch.py"
echo ""
echo "2. Wait for everything to start (30 seconds)"
echo ""
echo "3. Set initial pose (in RViz):"
echo "   a. Click '2D Pose Estimate' button in RViz toolbar"
echo "   b. Click on map where robot actually is"
echo "   c. Drag to set orientation"
echo ""
echo "4. Send navigation goal (in RViz):"
echo "   a. Click 'Navigate To Pose' button in RViz toolbar"
echo "   b. Click on map where you want robot to go"
echo "   c. Drag to set final orientation"
echo ""
echo "5. Robot will plan and execute path automatically!"
echo ""
echo "6. Optional: Manual control"
echo "   ros2 run teleop_twist_keyboard teleop_twist_keyboard"
echo "   (Use arrow keys to drive manually)"
